name: CI
env:
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn
      - run: yarn lint

  typescript:
    name: Run TypeScript for type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn
      - run: yarn typecheck
